name: upstream
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 5" # At 08:00 on Friday # https://crontab.guru/#0_8_*_*_5
  pull_request:
    types: [opened, synchronize]
    branches:
      - "*"
    paths:
      - .github/workflows/upstream.yml # this file

jobs:
  skeleton:
    steps:
      - run: echo "Hello, World!"
